### ISSUE TITLE
Acceptance Testing

### ISSUE THREAD

**Issue by Jeremylsw** [CS2103AUG2017-T16-B4/main#102]
Hi!!!! Here are some suggestions and issues I faced when using the application
**1. Add command**
- Does not have birthday validation checks - I'm able to add birthdays back-dated to 1990. I feel it would be good if the app checks for the date
- Since you're able to do the optional fields for edit, maybe do it for add too? I might not know the birthday or email of the person when adding the contag.
**2.  removeTag**
<img width="223" alt="screenshot 286" src="https://user-images.githubusercontent.com/28537653/32362838-1e9235be-c0a7-11e7-8dfb-cab9e381992c.png">
Does not remove tag from display list
**3. mail**
<img width="284" alt="screenshot 288" src="https://user-images.githubusercontent.com/28537653/32363012-106e4bde-c0a8-11e7-95aa-3cf4742b68d1.png">
User guide tells me to use email but app tells me to use index
<img width="326" alt="screenshot 287" src="https://user-images.githubusercontent.com/28537653/32363019-1c725272-c0a8-11e7-9ff0-5588f321a2a2.png">
Index does not work as well
<img width="414" alt="screenshot 289" src="https://user-images.githubusercontent.com/28537653/32363022-1fea6778-c0a8-11e7-85fa-37becee91347.png">

**4.toggle**
Toggle does not refresh browser screen even after right clicking and refreshing the page
<img width="958" alt="screenshot 290" src="https://user-images.githubusercontent.com/28537653/32363130-a78e7480-c0a8-11e7-8054-2825f2e02297.png">
<img width="953" alt="screenshot 291" src="https://user-images.githubusercontent.com/28537653/32363131-a87de5b0-c0a8-11e7-8fcd-dab76a3476e4.png">

**Comment by seankwekjk** [comment]
@Jeremylsw thanks for your feedback we will look to fix these issues
